# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ScreenshotTool
                                 A QGIS plugin
 Automated screenshot capture for geospatial features
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-02
        copyright            : (C) 2025 by Kofi Agyekum
        email                : adukofi73@yahoo.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ScreenshotTool class from file ScreenshotToolPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .screenshot_tool import ScreenshotToolPlugin
    return ScreenshotToolPlugin(iface)
